-- MOD 模組的載入順序（harness 用；遊戲本身照資料夾載入、靠 require 排依賴）。
-- 檔案還不存在的會略過；新增 Lua 檔就在這裡加一列。
return {
    { dir = "shared", name = "MinidoracatSafehouse/Contract" },
    { dir = "shared", name = "MinidoracatSafehouse/Settings" },
    { dir = "shared", name = "MinidoracatSafehouse/Recipes" },
    { dir = "server", name = "MinidoracatSafehouse/Audit" },
    { dir = "server", name = "MinidoracatSafehouse/Registry" },
    { dir = "server", name = "MinidoracatSafehouse/Native" },
    { dir = "server", name = "MinidoracatSafehouse/Health" },
    { dir = "server", name = "MinidoracatSafehouse/Identity" },
    { dir = "server", name = "MinidoracatSafehouse/Lifecycle" },
    { dir = "server", name = "MinidoracatSafehouse/Server" },
    { dir = "server", name = "MinidoracatSafehouse/Exclusions" },
    { dir = "server", name = "MinidoracatSafehouse/Claims" },
    { dir = "server", name = "MinidoracatSafehouse/Reconcile" },
    { dir = "server", name = "MinidoracatSafehouse/Migration" },
    { dir = "server", name = "MinidoracatSafehouse/Admin" },
    { dir = "server", name = "MinidoracatSafehouse/Calibrate" },
    { dir = "server", name = "MinidoracatSafehouse/Deeds" },
    { dir = "server", name = "MinidoracatSafehouse/Sharing" },
    { dir = "server", name = "MinidoracatSafehouse/Permissions" },
    { dir = "server", name = "MinidoracatSafehouse/Economy" },
    { dir = "client", name = "MinidoracatSafehouse/Mirror" },
    { dir = "client", name = "MinidoracatSafehouse/Client" },
    { dir = "client", name = "MinidoracatSafehouse/Select" },
    { dir = "client", name = "MinidoracatSafehouse/CreatePanel" },
    { dir = "client", name = "MinidoracatSafehouse/SharingPage" },
    { dir = "client", name = "MinidoracatSafehouse/ManagerWindow" },
    { dir = "client", name = "MinidoracatSafehouse/SlotsWindow" },
    { dir = "client", name = "MinidoracatSafehouse/AdminPanel" },
    { dir = "client", name = "MinidoracatSafehouse/PermissionsClient" },
    { dir = "client", name = "MinidoracatSafehouse/Entry" },
}
